apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-asp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: kdeit/aspapi
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-config