apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: postgres
data:
  DB_HOST: postgres-postgresql
  DB_PORT: "5432"
  DB_NAME: otus
  DB_USER: postgres
  BILLING_DB_HOST: postgres-postgresql
  BILLING_DB_PORT: "5432"
  BILLING_DB_NAME: otus_billing
  BILLING_DB_USER: postgres
  NOTIFICATION_DB_HOST: postgres-postgresql
  NOTIFICATION_DB_PORT: "5432"
  NOTIFICATION_DB_NAME: otus_notification
  NOTIFICATION_DB_USER: postgres
  ORDER_DB_HOST: postgres-postgresql
  ORDER_DB_PORT: "5432"
  ORDER_DB_NAME: otus_order
  ORDER_DB_USER: postgres